apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: basic-example
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-example
    spec:
      serviceAccountName: default
      containers:
        - name: app
          image: "gcr.io/testing-268014/vault-demo:1.0"
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: "http://104.198.30.62:8200"
